### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by LinkinStars** [fcjr/alert#2]
# environment
MacOS 11.2

# describe
![20210819-105958](https://user-images.githubusercontent.com/19712692/130001126-d83f443b-57e4-4b29-8681-344fb3f40a91.png)

# test code
```go
_ = alert.Info("Example 中文标题", "Example 中文消息")
```

Maybe, because the utf-8 encoding is not being used.
I will try to fix it in macos, but I don't have a test environment for Windows. I don't know if it have the same problem in Windows. 

PS: This is a good project for me.

**Comment by fcjr** [comment]
Thanks for the contribution @LinkinStars, apologies for never getting back to this!

Fixed by #3.
